from cyberaudit.main import app


def test_domain_expansion_openapi_contains_required_routes() -> None:
    routes = set(app.openapi()["paths"])
    expected = {
        "/api/v1/enterprise-connectors",
        "/api/v1/enterprise-connectors/{connector_id}",
        "/api/v1/enterprise-connectors/{connector_id}/test",
        "/api/v1/enterprise-connectors/{connector_id}/sync",
        "/api/v1/enterprise-connectors/{connector_id}/health",
        "/api/v1/enterprise-connectors/{connector_id}/executions",
        "/api/v1/identity/providers",
        "/api/v1/identity/users",
        "/api/v1/identity/users/{identity_id}",
        "/api/v1/identity/groups",
        "/api/v1/identity/roles",
        "/api/v1/identity/permissions",
        "/api/v1/identity/relationships",
        "/api/v1/identity/posture",
        "/api/v1/identity/risk",
        "/api/v1/identity/graph",
        "/api/v1/identity/active-directory/{collection}",
        "/api/v1/identity/entra/{collection}",
        "/api/v1/saas/{service}/{collection}",
        "/api/v1/cloud/accounts",
        "/api/v1/cloud/resources",
        "/api/v1/cloud/networks",
        "/api/v1/cloud/identities",
        "/api/v1/cloud/roles",
        "/api/v1/cloud/posture",
        "/api/v1/cloud/risk",
        "/api/v1/cloud/graph",
        "/api/v1/cloud/changes",
        "/api/v1/kubernetes/clusters",
        "/api/v1/kubernetes/workloads",
        "/api/v1/kubernetes/rbac",
        "/api/v1/kubernetes/posture",
        "/api/v1/container-runtime/hosts",
        "/api/v1/container-runtime/containers",
        "/api/v1/container-runtime/posture",
        "/api/v1/endpoints",
        "/api/v1/endpoints/{endpoint_id}",
        "/api/v1/endpoints/posture",
        "/api/v1/mobile-devices",
        "/api/v1/mobile-devices/{device_id}",
        "/api/v1/mobile-devices/posture",
        "/api/v1/zero-trust/overview",
        "/api/v1/zero-trust/assessments",
        "/api/v1/zero-trust/assessments/{assessment_id}",
        "/api/v1/zero-trust/evaluate",
        "/api/v1/zero-trust/trends",
    }
    assert expected <= routes
