"use client";
import { Button, Card } from "@cyberaudit/ui";
import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";
type Scenario={id:string;name:string};
type Result={statement:string;scenario:{baseline_risk:number;projected_risk:number;percentage_reduction:number}};
export default function RiskSimulatorPage(){const[name,setName]=useState("Plano de remediação prioritária");const[scenario,setScenario]=useState<Scenario>();const create=useMutation({mutationFn:()=>api<Scenario>("/risk-scenarios",{method:"POST",body:JSON.stringify({name,description:"Simulação sem alterar findings ou ativos.",selected_findings:[],selected_controls:["mfa","patching"],selected_asset_changes:[],assumptions:["Dados atuais do tenant"]})}),onSuccess:setScenario});const calculate=useMutation({mutationFn:()=>api<Result>(`/risk-scenarios/${scenario?.id}/calculate`,{method:"POST"})});return <Shell title="Simulador de Redução de Risco" eyebrow="Risk Engine 2.0"><Card className="p-5"><p className="max-w-3xl text-sm text-muted">Cria uma projeção imutável e explicável. A simulação não fecha findings, não altera ativos e não executa avaliações.</p><label className="mt-5 block max-w-xl text-xs text-muted">Nome do cenário<input className="field mt-2" value={name} onChange={event=>setName(event.target.value)}/></label><div className="mt-4 flex gap-3"><Button onClick={()=>create.mutate()} disabled={create.isPending}>Criar cenário</Button><Button className="button-secondary" disabled={!scenario||calculate.isPending} onClick={()=>calculate.mutate()}>Calcular projeção</Button></div>{calculate.data&&<div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Baseline" value={calculate.data.scenario.baseline_risk}/><Metric label="Projetado" value={calculate.data.scenario.projected_risk}/><Metric label="Redução" value={`${calculate.data.scenario.percentage_reduction}%`}/><p className="sm:col-span-3 text-sm text-primary">{calculate.data.statement}</p></div>}{(create.error||calculate.error)&&<p className="mt-4 text-sm text-red-300">Não foi possível concluir a simulação.</p>}</Card></Shell>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-lg border border-border p-4"><small className="text-muted">{label}</small><b className="mt-1 block text-xl text-cyan">{value}</b></div>}
