"""Canonical RBAC catalog: every permission the API checks, and the built-in roles.

``tests/test_rbac_catalog.py`` fails if an endpoint requires a permission that is
missing here, so a real (non-demo) installation can never ship an administrator
who is silently locked out of a module.
"""

from __future__ import annotations

PLATFORM_PERMISSION = "platform.manage"
PLATFORM_ROLE = "Platform Administrator"

ALL_PERMISSIONS: tuple[str, ...] = (
    "active_directory.read",
    "adapters.manage",
    "adapters.read",
    "ai_assistant.read",
    "ai_assistant.use",
    "ai_runtime.manage",
    "ai_runtime.read",
    "api_specifications.import",
    "apis.manage",
    "apis.read",
    "applications.manage",
    "applications.read",
    "approvals.read",
    "approvals.request",
    "approvals.review",
    "appsec_exceptions.read",
    "appsec_exceptions.request",
    "appsec_exceptions.review",
    "appsec_remediations.manage",
    "appsec_remediations.read",
    "appsec_risk.read",
    "assessment_schedules.manage",
    "assessment_schedules.read",
    "asset_changes.read",
    "asset_observations.read",
    "asset_suggestions.review",
    "assets.manage",
    "assets.read",
    "attack_paths.analyze",
    "attack_paths.read",
    "attack_paths.review",
    "audit_logs.read",
    "authentication_providers.manage",
    "authentication_providers.read",
    "authorizations.manage",
    "authorizations.read",
    "backups.manage",
    "backups.read",
    "cases.manage",
    "cases.read",
    "clients.manage",
    "clients.read",
    "cloud.graph.read",
    "cloud.posture.read",
    "cloud.read",
    "cloud.risk.read",
    "container_runtime.posture.read",
    "container_runtime.read",
    "controls.manage",
    "controls.read",
    "coverage.read",
    "dead_letters.manage",
    "dead_letters.read",
    "detections.manage",
    "detections.read",
    "diagnostics.export",
    "discovery_policies.manage",
    "discovery_policies.read",
    "endpoints.posture.read",
    "endpoints.read",
    "engagements.manage",
    "engagements.read",
    "enterprise_connectors.execute",
    "enterprise_connectors.manage",
    "enterprise_connectors.read",
    "enterprise_credentials.manage",
    "enterprise_exports.create",
    "enterprise_risks.manage",
    "enterprise_risks.read",
    "entra.read",
    "environments.manage",
    "environments.read",
    "events.ingest",
    "events.read",
    "evidence.download",
    "evidence.manage",
    "evidence.read",
    "feature_flags.manage",
    "feature_flags.read",
    "findings.manage",
    "findings.read",
    "frameworks.manage",
    "frameworks.read",
    "governance.manage",
    "governance.read",
    "grc.read",
    "grc_evidence.manage",
    "grc_evidence.read",
    "grc_exceptions.read",
    "grc_exceptions.request",
    "grc_exceptions.review",
    "hunts.manage",
    "hunts.read",
    "identity.graph.read",
    "identity.posture.read",
    "identity.read",
    "identity.risk.read",
    "imports.confirm",
    "imports.create",
    "imports.read",
    "incidents.manage",
    "incidents.read",
    "inventory.read",
    "jobs.cancel",
    "jobs.create",
    "jobs.execute",
    "jobs.read",
    "jobs.retry",
    "knowledge_graph.manage",
    "knowledge_graph.read",
    "kubernetes.posture.read",
    "kubernetes.read",
    "license.manage",
    "license.read",
    "mfa.manage",
    "mobile.posture.read",
    "mobile.read",
    "network_policies.manage",
    "network_policies.read",
    "network_zones.manage",
    "network_zones.read",
    "networks.manage",
    "networks.read",
    "notifications.read",
    "operations.read",
    "organizations.manage",
    "organizations.read",
    "playbooks.manage",
    "playbooks.read",
    "posture.read",
    "production_readiness.manage",
    "purple_team.manage",
    "purple_team.read",
    "releases.manage",
    "releases.read",
    "reports.manage",
    "reports.read",
    "repositories.manage",
    "repositories.read",
    "restores.manage",
    "restores.read",
    "retests.create",
    "retests.read",
    "risk.manage",
    "risk.read",
    "risk_scenarios.create",
    "roles.manage",
    "saas.read",
    "sboms.import",
    "sboms.read",
    "scan_profiles.manage",
    "scan_profiles.read",
    "scopes.manage",
    "scopes.read",
    "secrets.read",
    "secrets.review",
    "security_data.read",
    "security_gates.evaluate",
    "security_gates.manage",
    "security_gates.read",
    "services.read",
    "sessions.manage",
    "sessions.read",
    "soc.read",
    "software.read",
    "system_health.read",
    "telemetry.manage",
    "telemetry.read",
    "threat_intel.manage",
    "threat_intel.read",
    "updates.manage",
    "updates.read",
    "users.manage",
    "vulnerabilities.manage",
    "vulnerabilities.read",
    "vulnerability_feeds.manage",
    "vulnerability_feeds.read",
    "vulnerability_feeds.sync",
    "vulnerability_matches.review",
    "zero_trust.evaluate",
    "zero_trust.read",
)

_NEVER_VIEWER = {
    "audit_logs.read",
    "secrets.read",
    "sessions.read",
    "dead_letters.read",
    "backups.read",
    "restores.read",
    "operations.read",
    "authentication_providers.read",
    "telemetry.read",
    "feature_flags.read",
    "license.read",
}
_READS = tuple(c for c in ALL_PERMISSIONS if c.endswith(".read"))

ANALYST_WRITES = (
    "events.ingest",
    "detections.manage",
    "incidents.manage",
    "cases.manage",
    "hunts.manage",
    "playbooks.manage",
    "findings.manage",
    "evidence.manage",
    "grc_evidence.manage",
    "imports.create",
    "imports.confirm",
    "retests.create",
    "jobs.create",
    "jobs.execute",
    "jobs.cancel",
    "jobs.retry",
    "risk_scenarios.create",
    "attack_paths.analyze",
    "ai_assistant.use",
    "knowledge_graph.manage",
    "evidence.download",
    "grc_exceptions.request",
    "appsec_exceptions.request",
)
COMPLIANCE_WRITES = (
    "controls.manage",
    "frameworks.manage",
    "governance.manage",
    "grc_evidence.manage",
    "grc_exceptions.request",
    "grc_exceptions.review",
    "enterprise_risks.manage",
    "risk.manage",
    "reports.manage",
    "evidence.manage",
    "evidence.download",
    "ai_assistant.use",
)

ROLE_DEFINITIONS: dict[str, tuple[str, ...]] = {
    "Administrator": tuple(c for c in ALL_PERMISSIONS if c != PLATFORM_PERMISSION),
    PLATFORM_ROLE: (*ALL_PERMISSIONS, PLATFORM_PERMISSION),
    "Security Analyst": (
        *(_c for _c in _READS if _c not in {"audit_logs.read", "secrets.read"}),
        *ANALYST_WRITES,
    ),
    "Compliance Manager": (
        *(_c for _c in _READS if _c not in {"audit_logs.read", "secrets.read"}),
        *COMPLIANCE_WRITES,
    ),
    "Read-only Viewer": tuple(c for c in _READS if c not in _NEVER_VIEWER),
}
