"use client";
import { Card } from "@cyberaudit/ui";
import { useQuery } from "@tanstack/react-query";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";
type Risk={assets:number;overall_risk:number;critical_assets:number;high_assets:number;internet_exposed:number;unmanaged:number;calculation_version:string};
export default function RiskPage(){const {data,error}=useQuery({queryKey:["risk"],queryFn:()=>api<Risk>("/risk/overview")});const chart=[{name:"Crítico",value:data?.critical_assets??0,color:"#FF404D"},{name:"Alto",value:data?.high_assets??0,color:"#FF851B"},{name:"Restante",value:Math.max(0,(data?.assets??0)-(data?.critical_assets??0)-(data?.high_assets??0)),color:"#31F27C"}];return <Shell title="Risk Engine 2.0" eyebrow="Exposure Intelligence">{error&&<Card className="p-4 text-red-300">Não foi possível calcular o risco.</Card>}<div className="grid gap-4 md:grid-cols-3"><Card className="p-5 md:col-span-2"><p className="text-sm text-muted">Risco contextual da organização</p><strong className="mt-2 block text-5xl text-cyan">{data?.overall_risk.toFixed(1)??"—"}</strong><p className="mt-4 max-w-xl text-sm text-muted">Combina severidade técnica, exposição, reachability, criticidade do ativo, confiança e qualidade da evidência. Não substitui validação humana.</p><div className="mt-6 grid grid-cols-3 gap-3"><Metric label="Expostos" value={data?.internet_exposed}/><Metric label="Não geridos" value={data?.unmanaged}/><Metric label="Versão" value={data?.calculation_version}/></div></Card><Card className="p-5"><div className="h-56"><ResponsiveContainer><PieChart><Pie data={chart} dataKey="value" innerRadius={48} outerRadius={76}>{chart.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={{background:"#0B151C",border:"1px solid #17262F"}}/></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-4 text-xs text-muted">{chart.map(item=><span key={item.name}>{item.name}: {item.value}</span>)}</div></Card></div></Shell>}
function Metric({label,value}:{label:string;value:string|number|undefined}){return <div className="rounded-lg border border-border p-3"><small className="text-muted">{label}</small><b className="mt-1 block">{value??"—"}</b></div>}
