"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Badge, Button, Card } from "@cyberaudit/ui";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, Network, ShieldAlert, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";

const schema=z.object({
  engagement_id:z.string().min(1),scope_id:z.string().min(1),scan_profile_id:z.string().min(1),
  target_type:z.enum(["ip","cidr","domain","hostname","url","mobile_device","cloud_account","repository"]),
  target_value:z.string().min(1),technique:z.string().min(2),
  intensity:z.enum(["passive","low","normal","elevated","intrusive"]),approval_reason:z.string().optional(),
});
type Values=z.infer<typeof schema>;
type Page<T>={items:T[]};
type Profile={id:string;name:string;description:string;category:string;adapter_code:string;target_types:Values["target_type"][];default_intensity:Values["intensity"];maximum_intensity:string;timeout_seconds:number;network_access:boolean;default_configuration:Record<string,unknown>};
const categoryLabels:Record<string,string>={asset_inventory:"Inventário",dns_assessment:"DNS",tls_assessment:"TLS",http_security_headers:"HTTP",web_technology_detection:"Tecnologias",public_configuration:"Configuração Pública",external_result_import:"Importação",simulation:"Demonstração"};
const actions:Record<string,string[]>={asset_inventory:["Consolidar dados já conhecidos","Registar observações com origem"],dns_assessment:["Consultar registos do nome exato","Cache e limite de consultas"],tls_assessment:["Abrir uma ligação TLS","Recolher certificado e parâmetros negociados"],http_security_headers:["HEAD e GET limitado como fallback","Sanitizar cookies e headers"],web_technology_detection:["Observar headers e HTML limitado","Não inferir vulnerabilidades por tecnologia"],public_configuration:["Pedir um endpoint escolhido numa lista fechada"],simulation:["Simular localmente sem rede"]};

export default function NewJobPage(){
  const [result,setResult]=useState<{id:string;status:string;status_message:string}|null>(null);const [error,setError]=useState("");const [configuration,setConfiguration]=useState<Record<string,unknown>>({});
  const engagements=useQuery({queryKey:["engagements"],queryFn:()=>api<Page<{id:string;name:string;code:string}>>("/engagements?status=active")});
  const profiles=useQuery({queryKey:["profiles"],queryFn:()=>api<Page<Profile>>("/scan-profiles?page_size=100")});
  const {register,handleSubmit,watch,setValue,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{target_type:"ip",intensity:"passive",technique:"asset-inventory"}});
  const engagementId=watch("engagement_id");const profileId=watch("scan_profile_id");
  const scopes=useQuery({queryKey:["scopes",engagementId],queryFn:()=>api<Page<{id:string;name:string}>>(`/scopes?engagement_id=${engagementId}`),enabled:!!engagementId});
  const profile=useMemo(()=>profiles.data?.items.find(item=>item.id===profileId),[profiles.data,profileId]);
  useEffect(()=>{if(profile){setConfiguration(profile.default_configuration);setValue("intensity",profile.default_intensity);setValue("technique",profile.category.replaceAll("_","-"));if(profile.target_types[0])setValue("target_type",profile.target_types[0])}},[profile,setValue]);
  const submit=async(values:Values)=>{setError("");try{const job=await api<{id:string;status:string;status_message:string}>("/jobs",{method:"POST",body:JSON.stringify({...values,configuration})});setResult(job)}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível criar o job.")}};
  if(result)return <Shell title="Novo Job"><Card className="mx-auto max-w-2xl p-8 text-center"><CheckCircle2 className="mx-auto text-primary" size={42}/><h2 className="mt-4 text-xl font-semibold">Pedido avaliado pelo motor de políticas</h2><p className="mt-2 text-muted">{result.status_message}</p><Badge tone={result.status==="denied"?"danger":result.status==="pending_approval"?"warning":"success"} className="mt-4">{result.status}</Badge><div className="mt-6"><Link href={`/jobs/${result.id}`}><Button>Ver detalhe do job</Button></Link></div></Card></Shell>;
  return <Shell title="Novo Job"><form onSubmit={handleSubmit(submit)} className="space-y-4">
    <Card className="p-5"><Step n="1" title="Auditoria e âmbito"/><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Auditoria"><select className="field" {...register("engagement_id")}><option value="">Selecionar…</option>{engagements.data?.items.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></Field><Field label="Scope"><select className="field" {...register("scope_id")}><option value="">Selecionar…</option>{scopes.data?.items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div></Card>
    <Card className="p-5"><Step n="2" title="Categoria e perfil"/><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{profiles.data?.items.filter(item=>item.adapter_code!=="cyberaudit.external_result_import").map(item=><label key={item.id} className={`cursor-pointer rounded-xl border p-4 transition ${profileId===item.id?"border-primary bg-primary/[.06]":"border-border bg-surface hover:border-primary/30"}`}><input type="radio" value={item.id} className="sr-only" {...register("scan_profile_id")}/><span className="text-xs font-bold uppercase tracking-wider text-primary">{categoryLabels[item.category]??item.category}</span><b className="mt-2 block">{item.name}</b><small className="mt-1 block text-muted">{item.default_intensity} · {item.timeout_seconds}s</small></label>)}</div></Card>
    <Card className="p-5"><Step n="3" title="Alvo autorizado"/><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Tipo"><select className="field" {...register("target_type")}>{(profile?.target_types??["ip","domain","hostname","url"]).map(type=><option key={type} value={type}>{type}</option>)}</select></Field><Field label="Alvo" className="md:col-span-2"><input className="field font-mono" placeholder="Alvo explicitamente incluído no scope" {...register("target_value")}/></Field><Field label="Técnica"><input className="field" readOnly {...register("technique")}/></Field><Field label="Intensidade"><select className="field" {...register("intensity")}><option value="passive">Passiva</option><option value="low">Baixa</option>{profile?.adapter_code==="cyberaudit.demo_assessment"&&<option value="normal">Normal</option>}</select></Field><Field label="Motivo de aprovação"><input className="field" {...register("approval_reason")}/></Field></div></Card>
    {profile&&<Card className="p-5"><Step n="4" title="Limites e configuração permitida"/><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-border bg-surface p-4"><h3 className="flex items-center gap-2 font-semibold"><ShieldCheck size={17} className="text-primary"/>Ações realizadas</h3><ul className="mt-3 space-y-2 text-sm text-muted">{(actions[profile.category]??["Avaliação limitada pelo perfil"]).map(item=><li key={item}>• {item}</li>)}</ul><p className="mt-4 text-xs text-muted">Não realiza exploração, autenticação, brute force, crawling profundo, expansão de alvos ou comandos.</p></div><div className="rounded-lg border border-border bg-surface p-4"><h3 className="flex items-center gap-2 font-semibold"><Network size={17} className="text-cyan"/>Política calculada no backend</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><Info l="Timeout" v={`${profile.timeout_seconds}s`}/><Info l="Rede" v={profile.network_access?"Restrita":"Desativada"}/><Info l="Redirects" v={profile.network_access?"0–2, revalidados":"0"}/><Info l="Resposta" v={profile.network_access?"64–256 KiB":"N/A"}/></dl><Configuration profile={profile} value={configuration} onChange={setConfiguration}/></div></div><div className="mt-4 flex gap-2 rounded-lg border border-primary/20 bg-primary/[.05] p-3 text-sm text-muted"><ShieldAlert size={18} className="text-primary"/>O frontend só escolhe valores do schema. Os limites máximos são ignorados se enviados pelo cliente.</div></Card>}
    {error&&<div role="alert" className="rounded-lg border border-critical/30 bg-critical/10 p-3 text-red-300">{error}</div>}{Object.keys(errors).length>0&&<p className="text-sm text-critical">Revise os campos obrigatórios.</p>}<div className="flex justify-end"><Button disabled={isSubmitting||!profile}>{isSubmitting?"A avaliar política…":"Validar scope e criar job"}</Button></div>
  </form></Shell>
}
function Configuration({profile,value,onChange}:{profile:Profile;value:Record<string,unknown>;onChange:(value:Record<string,unknown>)=>void}){if(profile.category==="http_security_headers"||profile.category==="web_technology_detection")return <div className="mt-4"><select className="field" value={String(value.scheme??"https")} onChange={e=>onChange({...value,scheme:e.target.value})}><option value="https">HTTPS</option><option value="http">HTTP</option></select><p className="mt-2 text-xs text-muted">Para URLs é usado exatamente o path autorizado; para domínios é usada apenas a raiz.</p></div>;if(profile.category==="public_configuration")return <select className="field mt-4" value={String(value.endpoint??"/.well-known/security.txt")} onChange={e=>onChange({...value,endpoint:e.target.value})}><option value="/.well-known/security.txt">security.txt</option><option value="/robots.txt">robots.txt</option><option value="/sitemap.xml">sitemap.xml</option><option value="/manifest.json">manifest.json</option></select>;return <p className="mt-4 text-xs text-muted">Configuração fechada do perfil: {Object.entries(value).map(([key,item])=>`${key}=${Array.isArray(item)?item.join(","):String(item)}`).join(" · ")}</p>}
function Step({n,title}:{n:string;title:string}){return <div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-primary text-sm font-bold text-background">{n}</span><h2 className="font-semibold">{title}</h2></div>}
function Field({label,children,className=""}:{label:string;children:React.ReactNode;className?:string}){return <label className={`block text-sm ${className}`}><span className="mb-1.5 block text-muted">{label}</span>{children}</label>}
function Info({l,v}:{l:string;v:string}){return <div><dt className="text-xs text-muted">{l}</dt><dd>{v}</dd></div>}
