"use client";
import { Badge, Card } from "@cyberaudit/ui";
import { useQuery } from "@tanstack/react-query";
import { Database, HardDrive, Radio, Server } from "lucide-react";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";
type Health={status:string;components:{api:string;frontend:string;postgresql:string;redis:string;workers:string;runners:string;storage:string;vulnerability_feeds:string;scheduler:string;notifications:string;migrations:string;version:string}};
export default function SystemHealth(){const {data,error}=useQuery({queryKey:["system-health"],queryFn:()=>api<Health>("/system-health"),refetchInterval:10_000});const components=data?.components;return <Shell title="Health Center" eyebrow="Sistema / Observabilidade">{error&&<Card className="p-4 text-red-300">Health Center indisponível.</Card>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><HealthCard icon={Database} label="PostgreSQL" value={components?.postgresql}/><HealthCard icon={Radio} label="Redis" value={components?.redis}/><HealthCard icon={Server} label="Worker" value={components?.workers}/><HealthCard icon={HardDrive} label="Storage" value={components?.storage}/></div><Card className="mt-4 p-5"><h2 className="text-sm font-semibold">Dependências operacionais</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><Row label="API" value={components?.api}/><Row label="Vulnerability feeds" value={components?.vulnerability_feeds}/><Row label="Runners" value={components?.runners}/><Row label="Scheduler" value={components?.scheduler}/><Row label="Migration" value={components?.migrations}/><Row label="Versão" value={components?.version}/></div></Card></Shell>}
function HealthCard({icon:Icon,label,value}:{icon:typeof Database;label:string;value?:string}){const ok=["ok","online","healthy"].includes(value??"");return <Card className="p-5"><Icon className={ok?"text-primary":"text-high"}/><p className="mt-4 text-sm text-muted">{label}</p><Badge className="mt-2" tone={ok?"success":"warning"}>{value??"a verificar"}</Badge></Card>}
function Row({label,value}:{label:string;value?:string}){return <div className="flex justify-between rounded-lg border border-border p-3 text-sm"><span>{label}</span><span className="text-muted">{value??"—"}</span></div>}
